version: "2.3"

services:

  postgres:
    image: postgres:12.0
    mem_limit: 200M
    container_name: carpet_cleaner_postgres
    restart: always
    ports:
      - "25432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: carpet_cleaner_keycloak
      DB_USER: carpet_cleaner_keycloak
      DB_SCHEMA: public
      DB_PASSWORD: 111
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 18080:8080
    depends_on:
      - postgres

  carpet-cleaner:
    image: carpet_cleaner:0.0.1
    environment:
      CARPET_CLEANER_DB_URL: jdbc:postgresql://postgres:5432/carpet_cleaner
      CARPET_CLEANER_DB_USERNAME: carpet_cleaner
      CARPET_CLEANER_DB_PASSWORD: 111
    ports:
      - 8181:8080
    depends_on:
      - postgres
      - keycloak

  carpet-cleaner-client:
    image: carpet-cleaner-client:0.0.1
    environment:
      CARPET_CLEANER_API_HOST: "carpet-cleaner"
      CARPET_CLEANER_API_PORT: "8080"
    ports:
      - 9797:80
    depends_on:
      - postgres
      - keycloak
      - carpet-cleaner