version: "2.3"

services:
  carpet-cleaner-client:
    image: carpet-cleaner-client:0.0.1
    environment:
      CARPET_CLEANER_API_HOST: "carpet-cleaner"
      CARPET_CLEANER_API_PORT: "8080"
    ports:
      - 9797:80
