version: "2.3"

services:
  carpet-cleaner-client:
    image: nu/carpet-cleaner:0.0.1
    restart: always
    ports:
      - "9797:80"
    environment:
      KMF_API_HOST: "carpet-cleaner-server"
      KMF_API_PORT: "8080"
